### PR TITLE
Deploy contracts to Ethereum Sepolia

### PR DESCRIPTION
**Pull request by guidanoli**
Contracts were also verified using Etherscan's API.

### CODE REVIEW

**Comment by tuler** [comment]
Is it better to combine with #308 ?

**Comment by guidanoli** [comment]
> Is it better to combine with #308 ?

Will merge this PR, then adapt #308, and merge that.

**Comment by tuler** [comment]
Don't we need another release candidate?

**Comment by guidanoli** [comment]
> Don't we need another release candidate?

Sorry, I was waiting for #308 before releasing an RC.

**Pull request merged**
