### PR TITLE
Support base sepolia

### PR DESCRIPTION
**Pull request by tuler**

### CODE REVIEW

**Comment by guidanoli** [comment]
Will this go to a `1.3.1` or to a `1.4.0`?

**Comment by tuler** [comment]
I considered going to 1.3.1

**Comment by tuler** [comment]
> I considered going to 1.3.1

If you consider 1.3.0 should have base sepolia as well as base mainnet, it could be considered a patch.

**Comment by guidanoli** [comment]
Ok, fair enough.

**Review by guidanoli — APPROVED** [review]

**Pull request merged**
