### PR TITLE
Merge Cartesi Contracts into Rollux on Syscoin's Tanenbaum Testnet

### PR DESCRIPTION
**Pull request by sandhilt**
## Overview

This pull request integrates the Cartesi contracts into the Rollux environment, leveraging Syscoin's Tanenbaum testnet. This merge signifies a pivotal step in our ongoing efforts to enhance interoperability and expand the capabilities of our blockchain ecosystem.

## Request for Review

I invite team members to review the changes and provide their valuable feedback. Special attention to contract integrations, code compatibility, and performance optimizations would be highly appreciated.
Please let me know if need some refinements.

### CODE REVIEW

**Comment by pedroargento** [comment]
I see no problem merging this, but the problem is making it clear what version of rollups-contracts this deployments refer too. Those deployments contain changes that are not yet merged in the code base.

Thoughts, @guidanoli and @tuler?

**Comment by tuler** [comment]
If it's for rollups V2 I'd wait until the very end of the release processo, when you freeze the code

**Comment by guidanoli** [comment]
First, thanks for the PR!
Second, I agree with @tuler in that it would be safer if we synced the deployment process with the rest of the networks we currently support. Traditionally, this happens after we "freeze" the contracts (i.e. no changes are made to them until the next release cycle starts).

**Comment by guidanoli** [comment]
Just a heads-up: we moved everything inside `onchain/rollups` to the repository root. :-)

**Comment by guidanoli** [comment]
@sandhilt @fabiooshiro Does this still make sense for v2? Are you still working on the integration with Syscoin?

**Comment by fabiooshiro** [comment]
Our main focus is to provide a convenience layer to v2, so the Syscoin integration needs to align with this version. We'll likely need to do the Syscoin integration after this update.

**Pull request merged**
