### PR TITLE
Deploy to base network

### PR DESCRIPTION
**Pull request by tuler**
I deployed all contracts to base.
They are also verified at https://basescan.org

The base branch of this PR is `release/1.2.x`, but I guess a correct one should be `release/1.3.x`.
Not sure what is your process to do that.
I also did not add a changeset or changed any versioning file yet.

### CODE REVIEW

**Comment by tuler** [comment]
Not sure why test broke. Do you have any idea?

**Comment by guidanoli** [comment]
It's a problem with proof generation system. We've fixed it on `main`. Let me fix that real quick on this branch.

**Review by guidanoli — DISMISSED** [review]

**Comment by tuler** [comment]
How are you handling changesets for a 1.x?
Do you want to create a `realease/1.3.x` branch and change the base branch to it?

**Comment by tuler** [comment]
Changed base branch to `release/1.3.x`

**Comment by guidanoli** [comment]
> How are you handling changesets for a 1.x?

There are CI jobs ready to trigger for `main`, `release/*` and `prerelease/*` branches.
The `CHANGELOG` file will naturally get out-of-sync, but GitHub Releases will list all.

**Comment by tuler** [comment]
What I'm not understanding is that the `release/1.x` branches do not have changesets installed or the `.changeset` folder.

**Comment by guidanoli** [comment]
From what I've checked, `release/1.1.x` doesn't have changesets, but `release/1.2.x` (and now, `release/1.3.x`) do. You can find the `.changesets` folder at `onchain/rollups`. These also have the CI set up for releasing packages with `changeset publish`.

**Review by guidanoli — APPROVED** [review]

**Pull request merged**
