### PR TITLE
refactor!: remove unnecessary contracts/deployments

### PR DESCRIPTION
**Pull request by guidanoli**

### CODE REVIEW

**Comment by guidanoli** [comment]
## Removing deployment artifacts

I'll share here how I removed specific contracts from the deployment artifacts. Take `HistoryFactory` as an example.

```sh
git ls-files | grep HistoryFactory | xargs git rm
for file in export/abi/*.json; do jq 'del(.contracts.HistoryFactory)' $file > tmp; mv tmp $file; done
```

**Comment by guidanoli** [comment]
Don't mind the branch name `feature/shared-history`.
Its meaning has been disassociated from the name, but we'll keep using it anyway.

**Comment by pedroargento** [comment]
You forgot to delete `IHistory.sol`.

**Comment by guidanoli** [comment]
Removing `IHistory` now would break `Authority`.
We'll remove as soon as `Authority` no longer depends on it.

**Review by pedroargento — APPROVED** [review]

**Review by ZzzzHui — APPROVED** [review]

**Pull request merged**
